export const POSTS_DETAILS_COMMENTS = "POSTS_DETAILS_COMMENTS";
export const POSTS_FETCH_DETAILS = "POSTS_FETCH_DETAILS";
export const POSTS_FETCH_ALL = "POSTS_FETCH_ALL";
export const POSTS_FETCH_BY_SEARCH = "POSTS_FETCH_BY_SEARCH";
export const POSTS_CREATE = "POSTS_CREATE";
export const POSTS_UPDATE = "POSTS_UPDATE";
export const POSTS_LIKE = "POSTS_LIKE";
export const POSTS_DELETE = "POSTS_DELETE";
export const POSTS_FAIL = "POSTS_FAIL";

export const POSTS_START_LOADING = "POSTS_START_LOADING";
export const POSTS_END_LOADING = "POSTS_END_LOADING";
